"""empty message

Revision ID: 57bb7174f64a
Revises: c08edd0b00e9
Create Date: 2024-11-27 12:24:59.180089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57bb7174f64a'
down_revision = 'c08edd0b00e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['email_id'])
        batch_op.create_unique_constraint(None, ['contact_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
